apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - "*"
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  sourceNamespaces:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
