apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - SkipDryRunOnMissingResource=true
    - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.8.23
    helm:
      valueFiles:
      - $values/gitops/clusters/gke-demo-k8sgibdm/config/argocd/values.yaml
  - repoURL: https://github.com/michalzindulka/k8s-gitops-bootstrap.git
    targetRevision: main
    ref: values
